### ISSUE TITLE
Form a release

### ISSUE THREAD

**Issue by dm1tz** [kolunmi/sandbar#11]
Hi @kolunmi! I'm trying to [package sandbar for alpine linux.](https://gitlab.alpinelinux.org/alpine/aports/-/merge_requests/48459) Would it be possible to form an actual release? It'd ease the packaging process a lot. Thanks in advance.

**Comment by kolunmi** [comment]
Did it! This is the first time I've published a release, so please let me know if there are any issues

**Comment by dm1tz** [comment]
> Did it! This is the first time I've published a release, so please let me know if there are any issues

Yep, works like a charm. Thanks a lot!
