### ISSUE TITLE
RGBA handling

### ISSUE THREAD

**Issue by jeLee6gi** [kolunmi/sandbar#2]
This might not be a bug but I didn't expect this behavior. When I set the alpha channel of a color to 0, it's transparent only when I also set RGB to 0. Here are some examples, the background color is #008080.

| | A 00  | A 80 | A FF |
| - | ------------- | ------------- | ----------- |
| RGB 000000 | ![sandbar_00000000_crop](https://user-images.githubusercontent.com/9397810/224759562-70d80763-7b2f-4123-9c6f-69f2af73b90b.png) | ![sandbar_00000080_crop](https://user-images.githubusercontent.com/9397810/224759782-8f7af89a-10e8-4a32-8efc-c0daa7d50c6c.png) | ![sandbar_000000ff_crop](https://user-images.githubusercontent.com/9397810/224759820-73ef74a2-67dc-4082-84b2-3602987534f0.png) |
| RGB 808080 | ![sandbar_80808000_crop](https://user-images.githubusercontent.com/9397810/224759868-5bc93a3b-860b-4676-8133-7f7f8dfc96a3.png) | ![sandbar_80808080_crop](https://user-images.githubusercontent.com/9397810/224759913-b8ea83fa-866e-4722-8c9e-65feb4a7525f.png) | ![sandbar_808080ff_crop](https://user-images.githubusercontent.com/9397810/224759940-d85e9ca7-3392-4925-86ce-fcf2cf8aee6e.png) |
| RGB FFFFFF | ![sandbar_ffffff00_crop](https://user-images.githubusercontent.com/9397810/224759978-50f65d18-c1b0-48d1-be0f-edbf9ec32576.png) | ![sandbar_ffffff80_crop](https://user-images.githubusercontent.com/9397810/224760070-dfe35db5-4fae-44b9-b72f-b251ed47dada.png) | ![sandbar_ffffffff_crop](https://user-images.githubusercontent.com/9397810/224760109-fe7f9c13-7e1a-4c11-aa4f-34bbb8a1f48d.png) |

**Comment by kolunmi** [comment]
Hello! This has to do with pixman using pre-multiplied alpha. To get the desired effect you need to multiply the RGB components by `alpha / FF`. So for `80808000`: `80 * 00 / FF = 00` and thus `00000000`. I'm not sure how to address this issue since converting this way can introduce some inaccuracy.

**Comment by jeLee6gi** [comment]
Oh I was not familiar with premultiplied alpha. Thank you for the explanation, TIL.
