### ISSUE TITLE
font issues

### ISSUE THREAD

**Issue by jedugsem** [kolunmi/sandbar#5]
I have the feeling that something with text rendering is wrong, because the text in the bar seems much smaller that the same fontsize in for example somebar, or i3bar river.

**Comment by jedugsem** [comment]
another problem i have, is that the text seem to have much more padding below than above which makes it look wierd

**Comment by jedugsem** [comment]
really great project btw

**Comment by jeLee6gi** [comment]
Which font are you using? I am using FiraCode and didn't notice any issues with text rendering.

**Comment by kolunmi** [comment]
@jedugsem Could you provide a screenshot demonstrating the padding issue?

**Comment by jedugsem** [comment]
Sry for being late, this originated from i think somebar looking diffrent , there seemed to be more padding above text in somebar, now i use sandbar for the time this issue has been open and now it feels normal. I now thats the most bad reason to open a issue. Sorry for that. Great Project
