### ISSUE TITLE
[Feature Request] FIFO handling

### ISSUE THREAD

**Issue by dm1tz** [kolunmi/sandbar#7]
Currently, communication with sandbar using FIFO file is achievable manually:
```
mkfifo $XDG_RUNTIME_DIR/sandbar-0
sandbar < $XDG_RUNTIME_DIR/sandbar-0 &
someblocks -s "$XDG_RUNTIME_DIR/sandbar-0" &
```

IMO, implementing a way to create and handle a named pipe within sandbar would ease communication greatly. For example, when this is implemented, a new flag that will redirect arguments to FIFO can be added. Thus, instead of executing `echo "all toggle-visibility" > $XDG_RUNTIME_DIR/sandbar-0` we can do something like `sandbar -command toggle-visibility`. 
For reference, please see [somebar realization](https://git.sr.ht/~raphi/somebar/tree/master/item/src/main.cpp#L232).

**Comment by kolunmi** [comment]
Hello! Sorry for the delay. I originally omitted this feature in favor of simpler external scripts as they afford greater levels of customization. If you would like to implement this feature yourself, however, I will be open to merging it. Thank you!

**Comment by dkwo** [comment]
@dm1tz You forgot to mention taht someblocks needs to be patched to work that way with sandbar and river :)
```
-      dprintf(somebarFd, "status %s\n", statusstr[0]);
+      dprintf(somebarFd, "all status %s\n", statusstr[0]);
```
